### ISSUE TITLE
Enrich Documentation: 完善 TiDB 字符串函数中文文档说明

### ISSUE THREAD

**Issue by Oreoxmt** [pingcap/docs-cn#15947]
欢迎参与完善优化 [TiDB 文档](https://docs.pingcap.com/zh/tidb/stable/)。您的文档完善优化对我们不断提升 TiDB 文档的用户体验非常重要。

## 概览

当前的 [TiDB 字符串函数文档](https://docs.pingcap.com/zh/tidb/dev/string-functions)为每个[支持的函数](https://docs.pingcap.com/zh/tidb/dev/string-functions#支持的函数)提供了基本信息，但没有详细的描述和示例。为了使 TiDB 字符串函数文档更全面、更易于用户使用，我们欢迎外部贡献者丰富每个字符串函数的说明。

## 目标

- 通过为每个函数提供详细的说明和使用示例，完善 TiDB 字符串函数文档。
- 确保文档内容的一致性和清晰。

## 所需技能

- 熟练掌握 SQL 和 TiDB 字符串函数。

## 贡献指南

1. 从 [sub-issue 列表](#sub-issue-列表)中选择两个字符串函数。
2. 点击跳转到这两个字符串函数对应的 sub-issue 链接。
3. 在 sub-issue 页面通过发表 `/assign` 评论将此 sub-issue 分配给自己。如果该 sub-issue 右上角的 Assignees 字段已显示有人认领，请重新选择一个 sub-issue。
4. 向 TiDB 中文文档仓库 [pingcap/docs-cn](https://github.com/pingcap/docs-cn/pulls) 提交 Pull Request (PR)。
5. 在创建 PR 时，请在 PR 描述中指明该 PR 解决了哪个问题，例如 "Fix #xxx"。

## sub-issue 列表

- [ ] Enrich instructions for string functions [ SPACE()](https://docs.pingcap.com/zh/tidb/dev/string-functions#space) and [STRCMP()](https://docs.pingcap.com/zh/tidb/dev/string-functions#strcmp)
- [ ] Enrich instructions for string functions [ SUBSTR()](https://docs.pingcap.com/zh/tidb/dev/string-functions#substr) and [SUBSTRING()](https://docs.pingcap.com/zh/tidb/dev/string-functions#substring)
- [ ] Enrich instructions for string functions [ SUBSTRING_INDEX()](https://docs.pingcap.com/zh/tidb/dev/string-functions#substring_index) and [TO_BASE64()](https://docs.pingcap.com/zh/tidb/dev/string-functions#to_base64)
- [ ] Enrich instructions for string functions [ TRANSLATE()](https://docs.pingcap.com/zh/tidb/dev/string-functions#translate) and [TRIM()](https://docs.pingcap.com/zh/tidb/dev/string-functions#trim)
- [ ] Enrich instructions for string functions [ UCASE()](https://docs.pingcap.com/zh/tidb/dev/string-functions#ucase) and [UNHEX()](https://docs.pingcap.com/zh/tidb/dev/string-functions#unhex)
- [ ] Enrich instructions for string functions [ UPPER()](https://docs.pingcap.com/zh/tidb/dev/string-functions#upper) and [WEIGHT_STRING()](https://docs.pingcap.com/zh/tidb/dev/string-functions#weight_string)

## 更多信息

- 关于如何创建 PR 的详情，请参考 [TiDB 中文文档贡献指南](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md?rgh-link-date=2023-12-16T12%3A24%3A15Z)。
- 请确保在 TiDB 中测试您提供的文档描述和示例。要快速开始使用 TiDB 或 TiDB Cloud，请参考以下文档：
     - [TiDB Cloud 快速上手指南 | PingCAP 文档中心](https://docs.pingcap.com/tidbcloud/tidb-cloud-quickstart)（英文版）
    - [TiDB 数据库快速上手指南 | PingCAP 文档中心](https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb)
- **不要**从其他数据库的文档中复制文档描述或示例。

非常感谢您对完善 TiDB 文档的贡献！感谢您帮助改进 TiDB 文档用户体验。
